### ISSUE TITLE
AttributeError: 'function' object has no attribute 'var'

### ISSUE THREAD

**Issue by wangguangyuan** [DSaurus/DeepMultiCap#1]
您好感谢开源这么优秀的工作，我在跑你的程序的时候报错
Traceback (most recent call last):
  File "render_smpl.py", line 97, in <module>
    render_smpl_global_normal(args.dataroot, args.obj_path, args.faces_path, res, args.yaw_list, args.flip_y, args.flip_normal)
  File "render_smpl.py", line 50, in render_smpl_global_normal
    camera = t3.Camera(res=res)
  File "/workspace/DeepMultiCap/taichi_render_gpu/taichi_three/transform.py", line 111, in __init__
    self.mask = ti.Vector.var(3, ti.f32, self.res)
AttributeError: 'function' object has no attribute 'var'

**Comment by DSaurus** [comment]
It seems like your taichi version is higher, you can try to downgrade taichi to 0.6.39.

**Comment by wangguangyuan** [comment]
@DSaurus 非常感谢您百忙之中回复,我试着安装taichi0.6.39版本, pip install taichi==0.6.39发现 pip 源里已经没有这个版本了无法安装, 能否更新个支持高版本的代码,或者我自己改的话我不太清楚改的地方多不多.

**Comment by DSaurus** [comment]
We run our test successfully with taichi==0.7.15, so you can try to install taichi==0.7.15.
